language: r
r: bioc-release
sudo: required
warnings_are_errors: false

bioc_packages:
  - BiocInstaller
  - AnnotationDbi
  - biomaRt
  - BiocGenerics
  - Biostrings
  - GenomicFeatures
  - GenomicRanges,
  - Rsamtools

after_success:
  - Rscript -e 'library(covr);codecov()'
